// Mocks generated by Mockito 5.4.6 from annotations
// in chatbot_app/test/domain/usecases/send_message_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:chatbot_app/domain/entities/message_entity.dart' as _i3;
import 'package:chatbot_app/domain/repositories/chat_repository.dart' as _i5;
import 'package:chatbot_app/domain/usecases/command_processor.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCommandResult_0 extends _i1.SmartFake implements _i2.CommandResult {
  _FakeCommandResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMessageEntity_1 extends _i1.SmartFake implements _i3.MessageEntity {
  _FakeMessageEntity_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CommandProcessor].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommandProcessor extends _i1.Mock implements _i2.CommandProcessor {
  MockCommandProcessor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<Map<String, String>> get languages =>
      (super.noSuchMethod(
            Invocation.getter(#languages),
            returnValue: <Map<String, String>>[],
          )
          as List<Map<String, String>>);

  @override
  _i4.Future<_i2.CommandResult> processMessage(String? message) =>
      (super.noSuchMethod(
            Invocation.method(#processMessage, [message]),
            returnValue: _i4.Future<_i2.CommandResult>.value(
              _FakeCommandResult_0(
                this,
                Invocation.method(#processMessage, [message]),
              ),
            ),
          )
          as _i4.Future<_i2.CommandResult>);
}

/// A class which mocks [ChatRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRepository extends _i1.Mock implements _i5.ChatRepository {
  MockChatRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i3.MessageEntity> sendMessage(String? content) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [content]),
            returnValue: _i4.Future<_i3.MessageEntity>.value(
              _FakeMessageEntity_1(
                this,
                Invocation.method(#sendMessage, [content]),
              ),
            ),
          )
          as _i4.Future<_i3.MessageEntity>);

  @override
  _i4.Future<List<_i3.MessageEntity>> getMessageHistory() =>
      (super.noSuchMethod(
            Invocation.method(#getMessageHistory, []),
            returnValue: _i4.Future<List<_i3.MessageEntity>>.value(
              <_i3.MessageEntity>[],
            ),
          )
          as _i4.Future<List<_i3.MessageEntity>>);

  @override
  _i4.Future<void> clearHistory() =>
      (super.noSuchMethod(
            Invocation.method(#clearHistory, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
